export const MAX_DIGITS = 9;
export const INVERT_SYMBOL = "+/-";
export const ALL_CLEAR_SYMBOL = "AC";

export const ActionTypes = {
  UPDATE_CURRENT_OPERAND: "UPDATE_CURRENT_OPERAND",
  UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
  EVALUATE_EXPRESSION: "EVALUATE_EXPRESSION",
  INVERT_NUMBER: "INVERT_NUMBER",
  CALCULATE_PERCENT: "PERCENT",
  ALL_CLEAR: "ALL_CLEAR",
  CLEAR: "CLEAR"
};
